version: '3'

services:
  web:
    build:
      dockerfile: ./web/docker/Dockerfile
      context: ./
    command: gunicorn CourseBot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/CourseBot
    expose:
      - 8000
    networks:
      - app
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0.33
    ports:
      - '3322:3306'
    environment:
      MYSQL_DATABASE: 'CourseBot'
      MYSQL_ROOT: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./web/mysql/data:/var/lib/mysql
      - ./web/mysql/dump:/dump
    networks:
      - app

  nginx:
    build: ./web/nginx
    volumes:
      - .:/CourseBot
    ports:
      - 1794:80
    depends_on:
      - web
    networks:
      - app

networks:
  app:
    driver: bridge
