# Generated by Django 3.1.1 on 2024-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_preference',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
