# Generated by Django 3.1.1 on 2024-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_interview_labormarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('contact', models.TextField(null=True, verbose_name='Контакти')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
