# Generated by Django 3.1.1 on 2024-04-02 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст пропозиції')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.userprofile')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
    ]
