# Generated by Django 3.1.1 on 2024-04-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='job_preference',
            new_name='preference',
        ),
    ]
