# Generated by Django 3.1.1 on 2024-04-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20240403_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='preference',
            field=models.TextField(null=True, verbose_name='Найголовніше у пошуку роботи'),
        ),
    ]
