# Generated by Django 3.1.1 on 2024-04-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20240403_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(null=True, verbose_name='Навички'),
        ),
    ]
