# Generated by Django 3.1.1 on 2024-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='tongue',
            field=models.TextField(null=True, verbose_name='Володіння мовами'),
        ),
    ]
