# Generated by Django 3.1.1 on 2024-04-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20240410_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='img',
            field=models.ImageField(blank=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='labormarket',
            name='img',
            field=models.ImageField(blank=True, upload_to='resumes/'),
        ),
    ]
